# Generated by Django 5.1.2 on 2024-10-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('resume_file', models.FileField(upload_to='results/')),
                ('image', models.ImageField(upload_to='pictures/')),
                ('about_me', models.TextField()),
            ],
        ),
    ]
