# Generated by Django 5.1.2 on 2024-10-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Home',
        ),
    ]
