# Generated by Django 5.1.2 on 2024-10-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('compnay_position', models.CharField(max_length=100)),
            ],
        ),
    ]
