# Generated by Django 5.1.2 on 2024-10-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_education_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('languages_used', models.CharField(max_length=100)),
                ('repo_link', models.CharField(max_length=200)),
                ('live_link', models.CharField(max_length=200)),
            ],
        ),
    ]
