# Generated by Django 5.1.2 on 2024-10-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month_year', models.CharField(max_length=100)),
                ('end_month_year', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('Institue_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month_year', models.CharField(max_length=100)),
                ('end_month_year', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_location', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
            ],
        ),
    ]
