# Generated by Django 5.1.2 on 2024-10-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default=1, upload_to='pictures/project'),
            preserve_default=False,
        ),
    ]
