# Generated by Django 5.1.2 on 2024-10-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_projects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='facebook_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='instagram_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='linkedin_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='twitter_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
