# Generated by Django 5.1.2 on 2024-10-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_home_address_home_email_home_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='github_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
